[package]
name = "rvector_core"
edition = "2021"
version.workspace = true
description.workspace = true
authors.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embeddings = { path = "../embeddings" }
storage = { path = "../storage" }
vector = { path = "../vector" }
configs = { path = "../configs" }
