[package]
name = "embeddings"
edition = "2021"
version.workspace = true
description.workspace = true
authors.workspace = true
documentation.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1" }
hf-hub = { version = "0.3", default-features = false }
ndarray = { version = "0.15", default-features = false }
ort = { version = "=2.0.0-rc.4", default-features = false, features = [
    "ndarray",
] }
rayon = { version = "1.10", default-features = false }
serde_json = { version = "1" }
tokenizers = { version = "0.19", default-features = false, features = ["onig"] }

[dev-dependencies]
criterion = "0.5.1"

[features]
default = ["ort-download-binaries", "online"]
online = ["hf-hub/online"]
ort-download-binaries = ["ort/download-binaries"]
ort-load-dynamic = ["ort/load-dynamic"]

[[bench]]
name = "embed"
harness = false

# [lib]
# name = "embeddings"
# path = "src/lib.rs"
