[package]
name = "embeddings"
edition = "2021"
version.workspace = true
description.workspace = true
authors.workspace = true
documentation.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# [lib]
# name = "embeddings"
# path = "src/main.rs"
