[package]
name = "configs"
edition = "2021"
version.workspace = true
description.workspace = true
authors.workspace = true
documentation.workspace = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
